news/urls.py
# pages/urls
from django.urls import path
from . import views

urlpatterns = [
    path('', views.NewsPageView.as_view(), name='news_list'),
]

personal_account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "personal_account"

urlpatterns = [
    path("", views.AccountPageView.as_view(), name="account"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.CustomRegistrationView.as_view(), name="signup"),
    path('plug/', views.CustomPlugView.as_view(), name="plug"),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name="personal_account/password_reset.html",
        email_template_name="personal_account/password_reset_email.html",
        success_url='/personal_account/password_reset/done/'
    ), name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="personal_account/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/',views.CustomPasswordResetConfirmView.as_view(),name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name="personal_account/password_reset_complete.html"), name="password_reset_complete"),
    path('<str:username>/profile_edit', views.ProfileUpdateView.as_view(), name='profile_edit'),
    path('<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
]

site_bw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler403 = "pages.views.handler403"
handler404 = "pages.views.handler404"
handler500 = "pages.views.handler500"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("pages.urls")),
    path("personal_account/", include("personal_account.urls")),
    # path("auth/", include("django.contrib.auth.urls")),
    # path(
    #     "auth/registration/",
    #     CreateView.as_view(
    #         template_name="registration/registration_form.html",
    #         form_class=UserCreationForm,
    #         success_url=reverse_lazy("personal_account:index"),
    #     ),
    #     name="registration",
    # ),
]

# Добавляем для работы медиа
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'img/fav/favicon.ico' %}" type="image/x-icon">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  
<header class="header">
    <div class="container">
        <nav class="nav">
            <a href="{% url 'about' %}" class="logo-link">
                <img src="{% static 'img/fav/favicon_cor.png' %}" class="logo">
            </a>
            
            <!-- Информационные кнопки -->
            <div class="info-buttons">
                <a href="{% url 'about' %}">Информация о проекте</a>
                <a href="{% url 'news' %}">Новости</a>
            </div>
            
            <!-- Кнопки авторизации -->
            <div class="info-buttons">
                {% if user.is_authenticated %}
                    <a href="{% url 'personal_account:user_profile' username=user.username %}">Профиль</a>
                    <form method="post" action="{% url 'personal_account:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="auth-btn">Выйти</button>
                    </form>
                {% else %}
                    <a href="{% url 'personal_account:login' %}" class="auth-btn">Войти</a>
                    <a href="{% url 'personal_account:signup' %}" class="auth-btn">Регистрация</a>
                {% endif %}
            </div>
        </nav>
    </div>
</header>
    
    <main class="main">
        <div class="container">
            {% block content %}
            {% endblock content %}
        </div>
    </main>
    
    <footer class="footer">
        <div class="container">
            <p>&copy; {% now "Y" %} Bestwaycoop. All rights reserved.</p>
            <a href="http://t.me/bw_bestwaycoop" style="text-decoration: none;">
                <svg width="20" height="20" viewBox="0 0 24 24" style="vertical-align: middle; margin-right: 5px;">
                    <path fill="currentColor" d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm4.64 6.8c-.15 1.58-.8 5.42-1.13 7.19-.14.75-.42 1-.68 1.03-.58.05-1.02-.38-1.58-.75-.88-.58-1.38-.94-2.23-1.5-.99-.65-.35-1.01.22-1.59.15-.15 2.71-2.48 2.76-2.69.03-.1.06-.2-.06-.3s-.35-.04-.5-.03c-.21.03-3.57 2.26-5.04 3.18-.48.3-.92.45-1.32.44-.43-.01-1.27-.24-1.89-.44-.75-.25-1.35-.38-1.3-.8.03-.27.4-.55 1.1-.85 4.43-1.94 7.37-3.22 11.2-4.96.53-.2 1.01-.3 1.45-.3.31.01.9.17.9.66.01.33-.33.76-.5 1.02z"/>
                </svg>
                <span>Наш Telegram</span>
            </a>
        </div>
    </footer>
    
</body>
</html>

templates/password_reset.html
{% extends "base.html" %}
{% block content %}
    <h2>Сброс пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.email.label_tag }}
        {{ form.email }}
        <button type="submit" >Отправить</button>
    </form>
{% endblock content %}

templates/password_reset_confirm.html
<h2>Введите новый пароль</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сменить пароль</button>
</form>

templates/password_reset_done.html
{% extends "base.html" %}
{% block content %}
      <h2>
        Письмо с инструкциями по восстановлению пароля отправлено
      </h2>
      <p>
        Мы отправили вам инструкцию по установке нового пароля
        на указанный адрес электронной почты (если в нашей базе данных есть такой адрес).
        Вы должны получить ее в ближайшее время.
      </p>
      <p>
        Если вы не получили письмо, пожалуйста,
        убедитесь, что вы ввели адрес с которым вы зарегистрировались,
        и проверьте папку со спамом.
      </p>
        <a href="{% url 'about' %}">Вернуться на главную</a>
{% endblock %}

templates/password_reset_sent.html
<h2>Проверьте почту</h2>
<p>Мы отправили вам письмо со ссылкой для восстановления пароля.</p>